# Generated by Django 3.2.6 on 2021-08-10 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departaments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Positions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Stores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Phone', models.CharField(max_length=15)),
                ('eMail', models.EmailField(max_length=100)),
                ('Address', models.CharField(max_length=100)),
                ('ZipCode', models.CharField(max_length=14)),
                ('City', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Store', models.CharField(max_length=10)),
                ('Sector', models.CharField(max_length=10)),
                ('Position', models.CharField(max_length=10)),
                ('Phone', models.CharField(max_length=15)),
                ('eMail', models.EmailField(max_length=100)),
                ('Address', models.CharField(max_length=100)),
                ('ZipCode', models.CharField(max_length=14)),
                ('City', models.CharField(max_length=100)),
            ],
        ),
    ]
